version: '3.8'
services:
  products-service:
    build: ./products-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/products_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  db:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: products_db

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
