spring:
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
        - id: orders-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**

        - id: admin-service
          uri: http://localhost:8084
          predicates:
            - Path=/admin/**

        - id: image-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/images/**